AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample

Resources:
  lambdaResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: testpipe-Native
      Role: arn:aws:iam::079862682662:role/PointSystemAurora
      Runtime: provided.al2
      Handler: hello.handler
      MemorySize: 128
      Timeout: 3
      CodeUri: ../target/cps-0.0.1-SNAPSHOT-native.zip
      AutoPublishAlias: active
